/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicDashboardRouteImport } from './routes/_public/dashboard'
import { Route as AdminContentRouteRouteImport } from './routes/admin/content/route'
import { Route as AdminContentIndexRouteImport } from './routes/admin/content/index'
import { Route as AdminContentPendingRouteImport } from './routes/admin/content/pending'
import { Route as AdminContentRoadmapSlugRouteImport } from './routes/admin/content/$roadmap.$slug'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDashboardRoute = PublicDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PublicRoute,
} as any)
const AdminContentRouteRoute = AdminContentRouteRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentIndexRoute = AdminContentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminContentRouteRoute,
} as any)
const AdminContentPendingRoute = AdminContentPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AdminContentRouteRoute,
} as any)
const AdminContentRoadmapSlugRoute = AdminContentRoadmapSlugRouteImport.update({
  id: '/$roadmap/$slug',
  path: '/$roadmap/$slug',
  getParentRoute: () => AdminContentRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin/content': typeof AdminContentRouteRouteWithChildren
  '/dashboard': typeof PublicDashboardRoute
  '/login': typeof PublicLoginRoute
  '/admin/content/pending': typeof AdminContentPendingRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/admin/content/$roadmap/$slug': typeof AdminContentRoadmapSlugRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof PublicDashboardRoute
  '/login': typeof PublicLoginRoute
  '/': typeof PublicIndexRoute
  '/admin/content/pending': typeof AdminContentPendingRoute
  '/admin/content': typeof AdminContentIndexRoute
  '/admin/content/$roadmap/$slug': typeof AdminContentRoadmapSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin/content': typeof AdminContentRouteRouteWithChildren
  '/_public/dashboard': typeof PublicDashboardRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/content/pending': typeof AdminContentPendingRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/admin/content/$roadmap/$slug': typeof AdminContentRoadmapSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/content'
    | '/dashboard'
    | '/login'
    | '/admin/content/pending'
    | '/admin/content/'
    | '/admin/content/$roadmap/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/login'
    | '/'
    | '/admin/content/pending'
    | '/admin/content'
    | '/admin/content/$roadmap/$slug'
  id:
    | '__root__'
    | '/_public'
    | '/admin/content'
    | '/_public/dashboard'
    | '/_public/login'
    | '/_public/'
    | '/admin/content/pending'
    | '/admin/content/'
    | '/admin/content/$roadmap/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminContentRouteRoute: typeof AdminContentRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/dashboard': {
      id: '/_public/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PublicDashboardRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/': {
      id: '/admin/content/'
      path: '/'
      fullPath: '/admin/content/'
      preLoaderRoute: typeof AdminContentIndexRouteImport
      parentRoute: typeof AdminContentRouteRoute
    }
    '/admin/content/pending': {
      id: '/admin/content/pending'
      path: '/pending'
      fullPath: '/admin/content/pending'
      preLoaderRoute: typeof AdminContentPendingRouteImport
      parentRoute: typeof AdminContentRouteRoute
    }
    '/admin/content/$roadmap/$slug': {
      id: '/admin/content/$roadmap/$slug'
      path: '/$roadmap/$slug'
      fullPath: '/admin/content/$roadmap/$slug'
      preLoaderRoute: typeof AdminContentRoadmapSlugRouteImport
      parentRoute: typeof AdminContentRouteRoute
    }
  }
}

interface PublicRouteChildren {
  PublicDashboardRoute: typeof PublicDashboardRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicDashboardRoute: PublicDashboardRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminContentRouteRouteChildren {
  AdminContentPendingRoute: typeof AdminContentPendingRoute
  AdminContentIndexRoute: typeof AdminContentIndexRoute
  AdminContentRoadmapSlugRoute: typeof AdminContentRoadmapSlugRoute
}

const AdminContentRouteRouteChildren: AdminContentRouteRouteChildren = {
  AdminContentPendingRoute: AdminContentPendingRoute,
  AdminContentIndexRoute: AdminContentIndexRoute,
  AdminContentRoadmapSlugRoute: AdminContentRoadmapSlugRoute,
}

const AdminContentRouteRouteWithChildren =
  AdminContentRouteRoute._addFileChildren(AdminContentRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminContentRouteRoute: AdminContentRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
