/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicDashboardRouteImport } from './routes/_public/dashboard'
import { Route as AdminRoadmapsIndexRouteImport } from './routes/admin/roadmaps/index'
import { Route as AdminRoadmapsRoadmapIndexRouteImport } from './routes/admin/roadmaps/$roadmap/index'
import { Route as AdminRoadmapsRoadmapTracksRouteRouteImport } from './routes/admin/roadmaps/$roadmap/tracks/route'
import { Route as AdminRoadmapsRoadmapTracksIndexRouteImport } from './routes/admin/roadmaps/$roadmap/tracks/index'
import { Route as AdminRoadmapsRoadmapTracksSlugRouteImport } from './routes/admin/roadmaps/$roadmap/tracks/$slug'
import { Route as AdminRoadmapsRoadmapTracksTrackSlugRouteImport } from './routes/admin/roadmaps/$roadmap/tracks/$track/$slug'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDashboardRoute = PublicDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PublicRoute,
} as any)
const AdminRoadmapsIndexRoute = AdminRoadmapsIndexRouteImport.update({
  id: '/roadmaps/',
  path: '/roadmaps/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRoadmapsRoadmapIndexRoute =
  AdminRoadmapsRoadmapIndexRouteImport.update({
    id: '/roadmaps/$roadmap/',
    path: '/roadmaps/$roadmap/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminRoadmapsRoadmapTracksRouteRoute =
  AdminRoadmapsRoadmapTracksRouteRouteImport.update({
    id: '/roadmaps/$roadmap/tracks',
    path: '/roadmaps/$roadmap/tracks',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminRoadmapsRoadmapTracksIndexRoute =
  AdminRoadmapsRoadmapTracksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminRoadmapsRoadmapTracksRouteRoute,
  } as any)
const AdminRoadmapsRoadmapTracksSlugRoute =
  AdminRoadmapsRoadmapTracksSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AdminRoadmapsRoadmapTracksRouteRoute,
  } as any)
const AdminRoadmapsRoadmapTracksTrackSlugRoute =
  AdminRoadmapsRoadmapTracksTrackSlugRouteImport.update({
    id: '/$track/$slug',
    path: '/$track/$slug',
    getParentRoute: () => AdminRoadmapsRoadmapTracksRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/': typeof PublicIndexRoute
  '/dashboard': typeof PublicDashboardRoute
  '/login': typeof PublicLoginRoute
  '/admin/roadmaps/': typeof AdminRoadmapsIndexRoute
  '/admin/roadmaps/$roadmap/tracks': typeof AdminRoadmapsRoadmapTracksRouteRouteWithChildren
  '/admin/roadmaps/$roadmap/': typeof AdminRoadmapsRoadmapIndexRoute
  '/admin/roadmaps/$roadmap/tracks/$slug': typeof AdminRoadmapsRoadmapTracksSlugRoute
  '/admin/roadmaps/$roadmap/tracks/': typeof AdminRoadmapsRoadmapTracksIndexRoute
  '/admin/roadmaps/$roadmap/tracks/$track/$slug': typeof AdminRoadmapsRoadmapTracksTrackSlugRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof PublicDashboardRoute
  '/login': typeof PublicLoginRoute
  '/': typeof PublicIndexRoute
  '/admin/roadmaps': typeof AdminRoadmapsIndexRoute
  '/admin/roadmaps/$roadmap': typeof AdminRoadmapsRoadmapIndexRoute
  '/admin/roadmaps/$roadmap/tracks/$slug': typeof AdminRoadmapsRoadmapTracksSlugRoute
  '/admin/roadmaps/$roadmap/tracks': typeof AdminRoadmapsRoadmapTracksIndexRoute
  '/admin/roadmaps/$roadmap/tracks/$track/$slug': typeof AdminRoadmapsRoadmapTracksTrackSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/dashboard': typeof PublicDashboardRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/roadmaps/': typeof AdminRoadmapsIndexRoute
  '/admin/roadmaps/$roadmap/tracks': typeof AdminRoadmapsRoadmapTracksRouteRouteWithChildren
  '/admin/roadmaps/$roadmap/': typeof AdminRoadmapsRoadmapIndexRoute
  '/admin/roadmaps/$roadmap/tracks/$slug': typeof AdminRoadmapsRoadmapTracksSlugRoute
  '/admin/roadmaps/$roadmap/tracks/': typeof AdminRoadmapsRoadmapTracksIndexRoute
  '/admin/roadmaps/$roadmap/tracks/$track/$slug': typeof AdminRoadmapsRoadmapTracksTrackSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/'
    | '/dashboard'
    | '/login'
    | '/admin/roadmaps/'
    | '/admin/roadmaps/$roadmap/tracks'
    | '/admin/roadmaps/$roadmap/'
    | '/admin/roadmaps/$roadmap/tracks/$slug'
    | '/admin/roadmaps/$roadmap/tracks/'
    | '/admin/roadmaps/$roadmap/tracks/$track/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/'
    | '/admin/roadmaps'
    | '/admin/roadmaps/$roadmap'
    | '/admin/roadmaps/$roadmap/tracks/$slug'
    | '/admin/roadmaps/$roadmap/tracks'
    | '/admin/roadmaps/$roadmap/tracks/$track/$slug'
  id:
    | '__root__'
    | '/admin'
    | '/_public'
    | '/_public/dashboard'
    | '/_public/login'
    | '/_public/'
    | '/admin/roadmaps/'
    | '/admin/roadmaps/$roadmap/tracks'
    | '/admin/roadmaps/$roadmap/'
    | '/admin/roadmaps/$roadmap/tracks/$slug'
    | '/admin/roadmaps/$roadmap/tracks/'
    | '/admin/roadmaps/$roadmap/tracks/$track/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/dashboard': {
      id: '/_public/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PublicDashboardRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/roadmaps/': {
      id: '/admin/roadmaps/'
      path: '/roadmaps'
      fullPath: '/admin/roadmaps/'
      preLoaderRoute: typeof AdminRoadmapsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roadmaps/$roadmap/': {
      id: '/admin/roadmaps/$roadmap/'
      path: '/roadmaps/$roadmap'
      fullPath: '/admin/roadmaps/$roadmap/'
      preLoaderRoute: typeof AdminRoadmapsRoadmapIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roadmaps/$roadmap/tracks': {
      id: '/admin/roadmaps/$roadmap/tracks'
      path: '/roadmaps/$roadmap/tracks'
      fullPath: '/admin/roadmaps/$roadmap/tracks'
      preLoaderRoute: typeof AdminRoadmapsRoadmapTracksRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roadmaps/$roadmap/tracks/': {
      id: '/admin/roadmaps/$roadmap/tracks/'
      path: '/'
      fullPath: '/admin/roadmaps/$roadmap/tracks/'
      preLoaderRoute: typeof AdminRoadmapsRoadmapTracksIndexRouteImport
      parentRoute: typeof AdminRoadmapsRoadmapTracksRouteRoute
    }
    '/admin/roadmaps/$roadmap/tracks/$slug': {
      id: '/admin/roadmaps/$roadmap/tracks/$slug'
      path: '/$slug'
      fullPath: '/admin/roadmaps/$roadmap/tracks/$slug'
      preLoaderRoute: typeof AdminRoadmapsRoadmapTracksSlugRouteImport
      parentRoute: typeof AdminRoadmapsRoadmapTracksRouteRoute
    }
    '/admin/roadmaps/$roadmap/tracks/$track/$slug': {
      id: '/admin/roadmaps/$roadmap/tracks/$track/$slug'
      path: '/$track/$slug'
      fullPath: '/admin/roadmaps/$roadmap/tracks/$track/$slug'
      preLoaderRoute: typeof AdminRoadmapsRoadmapTracksTrackSlugRouteImport
      parentRoute: typeof AdminRoadmapsRoadmapTracksRouteRoute
    }
  }
}

interface AdminRoadmapsRoadmapTracksRouteRouteChildren {
  AdminRoadmapsRoadmapTracksSlugRoute: typeof AdminRoadmapsRoadmapTracksSlugRoute
  AdminRoadmapsRoadmapTracksIndexRoute: typeof AdminRoadmapsRoadmapTracksIndexRoute
  AdminRoadmapsRoadmapTracksTrackSlugRoute: typeof AdminRoadmapsRoadmapTracksTrackSlugRoute
}

const AdminRoadmapsRoadmapTracksRouteRouteChildren: AdminRoadmapsRoadmapTracksRouteRouteChildren =
  {
    AdminRoadmapsRoadmapTracksSlugRoute: AdminRoadmapsRoadmapTracksSlugRoute,
    AdminRoadmapsRoadmapTracksIndexRoute: AdminRoadmapsRoadmapTracksIndexRoute,
    AdminRoadmapsRoadmapTracksTrackSlugRoute:
      AdminRoadmapsRoadmapTracksTrackSlugRoute,
  }

const AdminRoadmapsRoadmapTracksRouteRouteWithChildren =
  AdminRoadmapsRoadmapTracksRouteRoute._addFileChildren(
    AdminRoadmapsRoadmapTracksRouteRouteChildren,
  )

interface AdminRouteRouteChildren {
  AdminRoadmapsIndexRoute: typeof AdminRoadmapsIndexRoute
  AdminRoadmapsRoadmapTracksRouteRoute: typeof AdminRoadmapsRoadmapTracksRouteRouteWithChildren
  AdminRoadmapsRoadmapIndexRoute: typeof AdminRoadmapsRoadmapIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminRoadmapsIndexRoute: AdminRoadmapsIndexRoute,
  AdminRoadmapsRoadmapTracksRouteRoute:
    AdminRoadmapsRoadmapTracksRouteRouteWithChildren,
  AdminRoadmapsRoadmapIndexRoute: AdminRoadmapsRoadmapIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface PublicRouteChildren {
  PublicDashboardRoute: typeof PublicDashboardRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicDashboardRoute: PublicDashboardRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
